service: ap
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
      handler: src/index.author.create
      events:
        - http:
            path: api/v1/author
            method: post
            cors: true
  list:
    handler: src/index.author.list
    events:
      - http:
          path: api/v1/author
          method: get
          cors: true
  get:
    handler: src/index.author.get
    events:
      - http:
          path: api/v1/author/{id}
          method: get
          cors: true
  update:
    handler: src/index.author.update
    events:
      - http:
          path: api/v1/author/{id}
          method: put
          cors: true
  delete:
    handler: src/index.author.delete
    events:
      - http:
          path: api/v1/author/{id}
          method: delete
          cors: true
  filter:
    handler: src/index.author.filter
    events:
      - http:
          path: api/v1/author/filter
          method: post
          cors: true
          
resources:
  Resources:
    APDBDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'author'
